<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function drupal_seamless_cilogon_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_logout_confirm') {
    $form['#submit'][] = 'drupal_seamless_cilogon_user_login_form_submit';
  }
}

/**
 * Submit handler for the user_logout_confirm form.
 */
function drupal_seamless_cilogon_user_login_form_submit($form, FormStateInterface $form_state) {
  //$form_state->setRedirect('drupal_seamless_cilogon.login');
}
